name: Windows Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.7
  FLUTTER_VERSION: 3.24.3

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Check Environment Variables
    - name: Verify Environment Variables
      run: |
        echo "BUILD_NUMBER: ${{ env.BUILD_NUMBER }}"
        echo "BUILD_VERSION: ${{ env.BUILD_VERSION }}"
        echo "PYTHON_VERSION: ${{ env.PYTHON_VERSION }}"
        echo "FLUTTER_VERSION: ${{ env.FLUTTER_VERSION }}"

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    # Verify Python Installation
    - name: Verify Python Version
      run: python --version

    # Install Python Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    # Verify Flutter Installation
    - name: Verify Flutter Version
      run: flutter --version

    # Run Flutter Doctor for Diagnostics
    - name: Verify Flutter Installation with Doctor
      run: flutter doctor

    # Build Step
    - name: Flet Build Windows
      run: |
        flutter config --no-analytics
        flet build windows --verbose --no-rich-output --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

    # Upload Windows Artifact
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: error
